# Epic Development Cycle Workflow — Team-Based Multi-Epic Orchestration
name: epic-cycle
description: "Team-based execution of the full BMAD development cycle across ALL remaining epics. Spawns worker agents for heavy phases (dev-story, code-review, testarch) to get fresh context per phase. Lead agent handles create-story, git commits, and sprint-status coordination."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/epic-cycle"
instructions: "{installed_path}/instructions.xml"
template: false

# Variables and inputs
variables:
  # Epic targeting — NO epic_num required; processes ALL non-done epics
  # Epic order: process in the order they appear in sprint-status.yaml (top to bottom)

  # Sprint tracking
  sprint_status: "{implementation_artifacts}/sprint-status.yaml"
  story_dir: "{implementation_artifacts}"

  # Cycle log output (master log across all epics)
  cycle_log: "{implementation_artifacts}/epic-cycle-log.md"

  # Team configuration
  team_name: "bmad-epic-pipeline"

  # Behavior controls
  auto_resolve_severity: "high,medium" # Auto-resolve these severities in code review
  max_rework_iterations: 2 # Max dev→review rework loops before escalating to user
  pause_conditions:
    - "ambiguous_requirements"
    - "design_choice_needed"
    - "constraint_risk" # security, compliance, performance, interoperability

# Sub-workflow paths (used in worker agent prompts)
sub_workflows:
  workflow_engine: "{project-root}/_bmad/core/tasks/workflow.xml"
  create_story:
    workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/create-story/workflow.yaml"
    description: "Prepare story with full developer context"
  dev_story:
    workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story/workflow.yaml"
    description: "Implement story tasks and tests"
  code_review:
    workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/code-review/workflow.yaml"
    description: "Adversarial code review with auto-fix"
  testarch_automate:
    workflow: "{project-root}/_bmad/bmm/workflows/testarch/automate/workflow.yaml"
    description: "Generate test automation coverage"
    optional: true

# Smart input file references
input_file_patterns:
  epics:
    description: "Epic files containing stories to process"
    whole: "{planning_artifacts}/*epic*.md"
    sharded: "{planning_artifacts}/*epic*/*.md"
    load_strategy: "FULL_LOAD"
  architecture:
    description: "Architecture for context"
    whole: "{planning_artifacts}/*architecture*.md"
    sharded: "{planning_artifacts}/*architecture*/*.md"
    load_strategy: "FULL_LOAD"

# Execution configuration
execution_hints:
  interactive: false # Minimize prompts — autonomous operation
  autonomous: true # Proceed without user input unless blocked
  iterative: true # Process multiple stories across multiple epics
  team_mode: true # Lead agent orchestrates worker agents
  subagent_mode: true # Workers execute individual workflow phases

# Workflow sequence definition (reference for lead orchestration)
workflow_sequence:
  - step: create-story
    execution: lead_direct # Lead handles directly (lightweight)
    workflow: "{sub_workflows.create_story.workflow}"
    description: "Prepare story with full developer context"
  - step: dev-story
    execution: worker_agent # Spawn dev-worker
    workflow: "{sub_workflows.dev_story.workflow}"
    description: "Implement story tasks and tests"
  - step: code-review
    execution: worker_agent # Spawn review-worker (fresh context, no implementation bias)
    workflow: "{sub_workflows.code_review.workflow}"
    description: "Adversarial code review with auto-fix"
    auto_resolve: true
  - step: git-commit-impl
    execution: lead_direct
    action: git_commit_push
    description: "Commit and push implementation"
    message_template: "feat({epic_num}.{story_num}): {story_title} - implementation complete"
  - step: testarch-automate
    execution: worker_agent # Spawn test-worker
    workflow: "{sub_workflows.testarch_automate.workflow}"
    description: "Generate test automation coverage"
    optional: true
  - step: git-commit-tests
    execution: lead_direct
    action: git_commit_push
    description: "Commit and push test automation"
    message_template: "test({epic_num}.{story_num}): {story_title} - automation tests"

standalone: true

tags:
  - automation
  - epic
  - development-cycle
  - orchestration
  - team-based
